id: P09AF8E99
initial_creation_type: input
source_metadata:
  title: Confession Series
  language: en
  description: 'Lotsawa House presents the following texts related to the practice
    of confession (bshags pa):'
  volume:
    096ad4df40dd480da14e41934a533a96:
      title: Daily Confession (from the Vajrapañjara Tantra)
      parent: Canonical Works
    9e87f708e46e4362807ee6ef916ded6e:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Canonical Works
    942e092748c4485ab75d008b32fd3100:
      title: The Lament of Rudra
      parent: Practices
    e249fad6e28647c592fc7d4dd1533a5a:
      title: The Noble Sūtra of the Teaching on the Four Factors
      parent: Canonical Works
    029e95466cea42dd99cd8c7e20ab519f:
      title: The Ultimate Inexpressible Confession (Yeshe Kuchokma)
      parent: Canonical Works
    97d0d3f4a3c243fab13d5db9353d02d2:
      title: Verses of Confession 'Düsum Deshekma'
      parent: Canonical Works
    17a6fee9898d401ea21f050a64bca2b8:
      title: Guide to the Practice of Narak Kong Shak
      parent: Commentaries
    a0f211ffc77a4bc0ad7991f0a66a35e8:
      title: A Topical Outline of the General Confession Spoken by the Five Great
        Sages
      parent: Outlines
    beaa83cd21444fefaf711dd8509708e8:
      title: Root Downfalls of the Vajra Vehicle
      parent: Practices
    cf855e1967f64023923305f4c8d8a4b5:
      title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
      parent: Practices
    d338e9d6c8be4009a5d520245c35673a:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Practices
    1ec6b5dc76714280b4c401d23101b35c:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      parent: Practices
    2f24a70394794cfa8d3bece3ab45d614:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: Practices
    222c1676a84642f6929482dbdf706960:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Practices
    2927f126f6b347ed9b40190c2e7a5e8d:
      title: A Discourse on the Confession of Harmful Deeds Spoken by Yama Dharmarāja
        to Karma Chakme
      parent: Practices
    23e39ef2e3cd456ca0f0cb13f7636437:
      title: Brief Confession to the Earth Lords
      parent: Practices
    1e0faa5b1cb44df29208fa8787b15757:
      title: A Method of Confessing and Pledging through the Four Powers
      parent: Practices
    df65828dc7144d1ba11e1012b1b94f6b:
      title: Rays of Moonlight to Dispel the Darkness of Misdeeds
      parent: Practices
    90facf16be3b4498b2dce30684a20434:
      title: Method of Confession based on the Four Powers
      parent: Practices
    a373003031e2437b8dc282a3bee91ff7:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Practices
    0ec11c34e6cf44a0b5f053454864ea2b:
      title: A Prayer to Recognize My Own Faults and Keep in Mind the Objects of Refuge
      parent: Prayer
created_at: '2022-03-01T03:17:51.735819'
last_modified_at: '2022-03-01T03:17:51.735825'
